image: python:3.9

services:
  - postgres:latest

variables:
  POSTGRES_DB: bike_rental_db
  POSTGRES_USER: django
  POSTGRES_PASSWORD: password
  DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB

before_script:
  - pip install poetry
  - poetry install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
