version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bike_rental_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn bike_rental.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://django:password@db:5432/bike_rental_db
      - SECRET_KEY=your_secret_key

volumes:
  postgres_data:
